name: hrp-env2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.5.2 # series.append deprecated in 2.0
  - matplotlib
  - requests
  - scipy
  - plotly
  - dash
  - flask
  - scikit-learn